global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 后端API服务监控
  - job_name: 'spider-backend'
    static_configs:
      - targets: ['host.docker.internal:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Redis监控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # MySQL监控
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:3306']

  # MongoDB监控
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']

  # MinIO监控
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: '/minio/v2/metrics/cluster'

  # Elasticsearch监控
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'

  # Node Exporter (如果需要系统级监控)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']