version: "3.8"

services:
  minio:
    image: minio/minio:latest
    container_name: crawler-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - crawler-network

  crawler-backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: crawler-backend
    ports:
      - "3000:3000"
    environment:
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin123
      - MINIO_BUCKET_NAME=crawler-data
      - MINIO_USE_SSL=false
    depends_on:
      - minio
    restart: on-failure
    networks:
      - crawler-network

  crawler-frontend:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    container_name: crawler-frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # 把 nginx 日志挂载出来
      - ./nginx/logs:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - crawler-backend
    restart: on-failure
    networks:
      - crawler-network

networks:
  crawler-network:
    driver: bridge