apiVersion: v1
kind: Secret
metadata:
  name: task-demo-database
  namespace: task-demo
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: k8s-task-demo
type: Opaque
stringData:
  POSTGRES_USER: task
  POSTGRES_PASSWORD: task
  POSTGRES_DB: taskdb
  DATABASE_URL: postgres://task:task@postgres:5432/taskdb?sslmode=disable
