apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-app
  namespace: task-demo
  labels:
    app.kubernetes.io/name: task-app
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: k8s-task-demo
automountServiceAccountToken: false
