apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: task-app
  namespace: task-demo
  labels:
    app.kubernetes.io/name: task-app
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: k8s-task-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: task-app
  minReplicas: 2
  maxReplicas: 6
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
