name = "cloudflare-workers-demo"
main = "src/index.ts"
compatibility_date = "2024-12-18"

[vars]
# 可选：环境变量

# 资源配置
[[d1_databases]]
binding = "DB"
database_name = "my-database"
database_id = "3baeb291-8dd7-4035-9a56-79beb06b628d"

[[kv_namespaces]]
binding = "KV"
id = "0bf96a04d5df47fbac1458db4b3ee1e1"

# R2 需要在 Cloudflare Dashboard 中启用
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "my-r2-bucket"
