# 开发环境Docker Compose配置
# 使用方法: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  # Backend开发模式
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    volumes:
      - ../backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run start:dev
    ports:
      - "3001:3001"
      - "9229:9229"  # Node.js调试端口

  # Frontend开发模式
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    ports:
      - "5173:5173"  # Vite开发服务器端口