import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import { A2uiCardList } from "./a2ui-card-list";

const payload = {
  topic: "a2ui + AGUI + CopilotKit",
  agent: "agui-learning-agent" as const,
  followUp: "Ask how V2 works without CopilotKit.",
  cards: [
    {
      id: "card-a2ui",
      question: "What is a2ui?",
      answer: "UI-ready content",
      tags: ["a2ui"],
      protocol: "a2ui" as const,
    },
  ],
};

describe("A2uiCardList", () => {
  it("renders the generated cards and follow-up", () => {
    render(<A2uiCardList payload={payload} title="Generated by AGUI" />);

    expect(screen.getByText("Generated by AGUI")).toBeInTheDocument();
    expect(screen.getByText("What is a2ui?")).toBeInTheDocument();
    expect(
      screen.getByText("Ask how V2 works without CopilotKit."),
    ).toBeInTheDocument();
  });
});
